dist: xenial

language: go

go: 
  - 1.13.x

env: 
  - GO111MODULE=on  

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -race ./...  # Run all the tests with the race detector enabled

# Handle git submodules yourself
git:
  submodules: false
  
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive