controller:
  naming_convention: kebab
    # define models repositories and parameters
  models:
    users:
      repository_name: external_postgres
    notifications:
      repository_name: mongo
  # define repositories credentials and connection properties
  repositories:
    external_postgres:
      driver_name: pq
      host: 10.0.1.36
      port: 5432
      username: app_user
      password: 1e21f2eca1!2#
      dbname: usersdb
    internal_postgres:
      driver_name: pq
      raw_url: postgresql://some_user:pass@127.0.0.1:5432/dbname?sslmode=disable
    mongo:
      driver_name: mongo
      host: 127.0.0.1
      port: 27017
      username: mgapp
      password: 123ac1e!
      dbname: appall
  # set default repository to 'internal_postgres'
  default_repository_name: internal_postgres
  # set processor to 'concurrent'
  processor_name: concurrent
  log_level: debug2
  # allow include only to two levels
  include_depth_limit: 2

